name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push backend image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/lostfound-backend ./lost-found-campus/backend
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/lostfound-backend

    - name: Build and push frontend image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/lostfound-frontend ./lost-found-campus/frontend
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/lostfound-frontend

    - name: Deploy to DigitalOcean via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.DIGITALOCEAN_HOST }}
        username: root
        key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
        script: |
          cd 5-final-tralalero-tralala
          git pull origin main
          docker-compose down
          docker-compose pull
          docker-compose up -d --build
